import React from 'react';
import './RescueReport.css';

const RescueReport = ({ report, onClose }) => {
  const formatTimestamp = (timestamp) => {
    return new Date(timestamp).toLocaleString();
  };

  const getUrgencyColor = (urgency) => {
    switch (urgency) {
      case 'high': return '#dc3545';
      case 'medium': return '#fd7e14';
      case 'low': return '#28a745';
      default: return '#6c757d';
    }
  };

  const downloadReport = () => {
    const reportData = `
STRAY ANIMAL RESCUE REPORT
========================

Timestamp: ${formatTimestamp(report.timestamp)}
Animal Type: ${report.animalType}
Issue: ${report.issue}
Location: ${report.location}
Urgency Level: ${report.urgency.toUpperCase()}

Recommendations:
${report.recommendations}

Generated by Curio AI Assistant
    `.trim();

    const blob = new Blob([reportData], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `rescue-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rescue-report-overlay">
      <div className="rescue-report">
        <div className="report-header">
          <h3>🚨 Rescue Report Generated</h3>
          <button className="close-button" onClick={onClose}>×</button>
        </div>
        
        <div className="report-content">
          <div className="report-field">
            <label>Timestamp:</label>
            <span>{formatTimestamp(report.timestamp)}</span>
          </div>
          
          <div className="report-field">
            <label>Animal Type:</label>
            <span className="capitalize">{report.animalType}</span>
          </div>
          
          <div className="report-field">
            <label>Issue:</label>
            <span className="capitalize">{report.issue}</span>
          </div>
          
          <div className="report-field">
            <label>Location:</label>
            <span>{report.location}</span>
          </div>
          
          <div className="report-field">
            <label>Urgency Level:</label>
            <span 
              className="urgency-badge"
              style={{ color: getUrgencyColor(report.urgency) }}
            >
              {report.urgency.toUpperCase()}
            </span>
          </div>
          
          <div className="report-field full-width">
            <label>Recommendations:</label>
            <div className="recommendations">
              {report.recommendations}
            </div>
          </div>
        </div>
        
        <div className="report-actions">
          <button className="download-button" onClick={downloadReport}>
            📄 Download Report
          </button>
          <button className="close-button-secondary" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default RescueReport; 